routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('index');
});

Route::get('/home', 'HomeController@index')->name('home');

// Wishlist
Route::resource('wishlists', 'WishListController');
Route::get('wishlists/{wishlist}/print-pdf', 'PrintController@printPDF')->name('wishlist.printpdf');


// Wishes
Route::resource('wishes', 'WishController');
Route::post('wishes/create/{id?}', 'WishController@create')->name('wishes.create');

// Share
Route::get('share/{id}', 'ShareController@show')->name('share.show');
Route::patch('share/reserve/{wish}', 'ShareController@reserve')->name('share.reserve');
Route::patch('share/delete-reserve/{wish}', 'ShareController@deleteReserve')->name('share.delete-reserve');

// Users
Route::get('profile/', 'UserController@show')->name('profile');
Route::patch('profile/{user}/', 'UserController@update')->name('users.update');
Route::patch('profile/password/{user}/', 'UserController@updatePassword')->name('users.update-password');
Route::delete('profile/delete/{user}/', 'UserController@destroy')->name('users.destroy');

// Auth
Auth::routes();

app/WishList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WishList extends Model
{
    protected $fillable = [
        'name', 'description',
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function wishes()
    {
        return $this->hasMany(Wish::class);
    }
}

app/Http/Controllers/WishListController.php
<?php

namespace App\Http\Controllers;

use App\WishList;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class WishListController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        abort(404);
    }

    public function create()
    {
        return view('wishlists.create');
    }

    public function store()
    {
        $wishlist = new WishList;
        $wishlist->fill(request()->all());
        $wishlist->share_id = uniqid();
        $wishlist->save();
        $wishlist->users()->attach(Auth::user()->id);

        session()->flash('success', __('Ønskelisten blev oprettet.'));
        return redirect('/home');
    }

    public function show(WishList $wishlist)
    {
        if (Auth::User()->isPartOfWishlist($wishlist)) {
            $wishes = $wishlist->wishes()->orderBy('created_at', 'desc')->get();
            return view('wishlists.show')->with('wishlist', $wishlist)->with('wishes', $wishes);
        } else {
            return abort(403);
        }
    }

    public function edit(WishList $wishlist)
    {
        if (Auth::User()->isPartOfWishlist($wishlist)) {
            return view('wishlists.edit', compact('wishlist'));
        } else {
            return abort(403);
        }
    }

    public function update(WishList $wishlist)
    {
        if (Auth::User()->isPartOfWishlist($wishlist)) {
            $wishlist->fill(request()->all());
            $wishlist->save();

            session()->flash('success', __('Ønskelisten blev opdateret.'));
            return redirect('/wishlists/' . $wishlist->id);
        } else {
            return abort(403);
        }
    }

    public function destroy(WishList $wishlist)
    {
        if (Auth::User()->isPartOfWishlist($wishlist)) {
            $wishlist->users()->detach();
            $wishlist->wishes()->delete();
            $wishlist->delete();

            session()->flash('success', __('Ønskelisten blev slettet.'));
            return redirect('/home');
        } else {
            return abort(403);
        }
    }

    public function printPDF(WishList $wishlist)
    {
        $data = [
            'title' => $wishlist->name,
            'description' => $wishlist->description,
            'wishes' => $wishlist->wishes->toArray(),
            'users' => $wishlist->users->toArray(),
        ];
        $pdf = PDF::loadView('pdf_view', $data);
        return $pdf->download($wishlist->name.'.pdf');
    }
}

resources/views/wishlists/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="header-account-page bg-primary d-flex align-items-end" data-offset-top="#header-main">
        <!-- Circles -->
        @include('partials.circles')
        <!-- Header -->
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Title -->
                    <div class="row align-items-center mb-4">
                        <div class="col-md-5 mb-4 mb-md-0">
                            <span class="h2 mb-0 text-white d-block">{{ __('Opret ønskeliste') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Create wishlist  -->
    <section class="slice bg-section-secondary">
        <div class="container mn-5">
            <div class="row">
                <div class="col-12">
                    <div class="card zindex-100">
                        <div class="card-body px-md-5 py-5">
                            <form method="POST" action="{{ route('wishlists.store') }}">
                                @csrf
                                <div class="row">
                                    <div class="col-12 col-md-7">
                                        <div class="form-group">
                                            <label for="name" class="form-control-label">{{ __('Navn på ønskeliste') }}</label>
                                            <input type="text" id="name" class="form-control" name="name" value="{{ old('name') }}" placeholder="{{__('Giv ønskelisten et navn...') }}" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="description" class="form-control-label">{{ __('Beskrivelse af ønskeliste') }}</label>
                                            <textarea  id="description" class="form-control" name="description" placeholder="{{__('Beskriv ønskelisten. Beskrivelsen vises for dem, du deler ønskelisten med...') }}">{{ old('description') }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-warning">{{ __('Opret ønskeliste') }}</button>
                                    <a href="{{ URL::previous() }}" class="btn btn-link text-muted">{{ __('Annuller') }}</a>
                                </div>
                                @if ($errors->any())
                                    <div class="small text-danger mt-3" role="alert">
                                        <strong>{{ $errors->first() }}</strong>
                                    </div>
                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/wishlists/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="header-account-page bg-primary d-flex align-items-end" data-offset-top="#header-main">
        <!-- Circles -->
        @include('partials.circles')
        <!-- Header  -->
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Title -->
                    <div class="row align-items-center mb-4">
                        <div class="col-md-5 mb-4 mb-md-0">
                            <span class="h2 mb-0 text-white d-block">{{ __('Rediger ønskeliste') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Edit wishlist  -->
    <section class="slice bg-section-secondary">
        <div class="container mn-5">
            <div class="row">
                <div class="col-12">
                    <div class="card zindex-100">
                        <div class="card-body px-md-5 py-5">
                            <form method="POST" action="{{ route('wishlists.update', ['id' => $wishlist->id]) }}">
                                @method('PATCH')
                                @csrf
                                <div class="row">
                                    <div class="col-12 col-md-7">
                                        <div class="form-group">
                                            <label for="name" class="form-control-label">{{ __('Navn på ønskeliste (påkrævet)') }}</label>
                                            <input type="text" id="name" class="form-control" name="name" value="{{ $wishlist->name }}" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="description" class="form-control-label">{{ __('Beskrivelse af ønskeliste') }}</label>
                                            <textarea  id="description" class="form-control" name="description">{{ $wishlist->description }}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-warning">{{ __('Gem') }}</button>
                                    <button type="button" class="btn btn-link text-muted">{{ __('Annuller') }}</button>
                                </div>
                                @if ($errors->any())
                                    <div class="small text-danger mt-3" role="alert">
                                        <strong>{{ $errors->first() }}</strong>
                                    </div>
                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/wishlists/index.blade.php
<section class="slice bg-section-secondary">
    <div class="container">
        <div class="actions-toolbar py-2 mb-4">
            <h5 class="mb-1">{{ __('Mine ønskelister') }}</h5>
            <p class="text-sm text-muted mb-0">{{ __('Opret, rediger og slet ønskelister') }}</p>
        </div>
        <div class="row">
            @forelse($wishlists as $wishlist)
                <div class="col-12 col-sm-6 col-lg-4 d-flex">
                    <div class="wishlist__item card hover-shadow-lg hover-translate-y-n3 flex-fill">
                        <div class="card-header text-center">
                            <h5 class="my-2"><a
                                        href="{{ route('wishlists.show', ['id' => $wishlist->id]) }}">{{ $wishlist->name }}</a>
                            </h5>
                        </div>
                        <div class="card-body">
                            @forelse($wishlist->wishes->reverse()->take(2) as $wish)
                                <div class="row flex-row @if(!$loop->last) mb-3 @endif">
                                    <div class="col-auto">
                                        <div class="avatar rounded-circle">
                                            @if($wish->image)
                                                <img class="h-100"
                                                     src="{{ asset($wish->image) }}">
                                            @else
                                                <img class="h-100 opacity-5"
                                                     src="{{ asset('images/svg/illustrations/gift.svg') }}">
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col d-flex mb-2 align-items-center">
                                        <div class="h6 text-sm mb-0">{{ str_limit($wish->name, 30, '...') }}</div>
                                    </div>
                                </div>
                            @empty
                                <div class="d-flex flex-column text-center align-items-center h-100 text-sm">
                                    {{ __('Der er endnu ingen ønsker oprettet.') }}
                                    <button data-target=".create-wish" data-toggle="modal" class="btn btn-outline-warning btn-sm mt-3"> {{ __('Opret nyt ønske') }}</button>
                                </div>
                            @endforelse
                            @if($wishlist->wishes->count() > 2)
                                <div class="text-muted text-sm mt-3">{{ $wishlist->wishes->count() - 2 }} @if(($wishlist->wishes->count() - 2) === 1) {{__('ønske')}} @else {{__('ønsker')}} @endif {{__('mere ...')}}</div>
                            @endif
                        </div>
                        <div class="card-footer">
                            <div class="actions d-flex justify-content-between">
                                <div>
                                    <form method="POST" class="delete action-item" id="form"
                                          onclick="return confirm('{{ __('Er du sikker du ønsker at slette ønskelisten?') }}')"
                                          action="{{ route('wishlists.destroy', ['id' => $wishlist->id]) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="action-item text-danger">
                                            <i class="far fa-trash-alt"></i>
                                        </button>
                                    </form>
                                </div>
                                <strong class="h6 text-sm d-flex align-items-center m-0 pr-2">
                                    <a href="{{ route('wishlists.show', ['id' => $wishlist->id]) }}">{{ __('Se ønskeliste') }}</a>
                                </strong>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                <div class="col-12 col-sm-6 col-lg-4 d-flex">
                    <div class="card flex-fill alert alert-warning" role="alert">
                        <div class="p-3">
                            <h5 class="alert-heading">
                                Velkommen!
                            </h5>
                            <div class="font-weight-bold mt-3">Kom godt igang med Wishful.</div>
                            <div class="my-3">Opret din første ønskeliste ... til dig selv, dine børn eller en helt
                                tredje.
                            </div>
                            <a href="{{ route('wishlists.create') }}" class="btn btn-sm btn-warning">Opret
                                ønskeliste</a>
                        </div>
                    </div>
                </div>
            @endforelse
            @if(!$wishlists->count() == 0)
                <div class="col-12 col-sm-6 col-lg-4 d-flex">
                    <a href="{{ route('wishlists.create') }}"
                       class="wishlist__item card border-md border-dashed bg-transparent shadow-none flex-fill">
                        <div class="card-body text-center d-flex flex-column align-items-center justify-content-center p-5">
                            <button type="button" class="btn btn-soft-dark rounded-circle btn-icon-only mr-0">
                                <span class="btn-inner--icon">
                                    <i class="fas fa-plus"></i>
                                </span>
                            </button>
                            <div class="mt-4 h6 text-muted bg-gra">{{ __('Opret ny ønskeliste') }}</div>
                        </div>
                    </a>
                </div>
            @endif
        </div>
    </div>
</section>

resources/views/wishlists/show.blade.php
@extends('layouts.app')

@section('content')
    <!-- Header -->
    <section class="header-account-page bg-primary d-flex align-items-end" data-offset-top="#header-main">
        <div class="container pt-4 pt-lg-0">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Title -->
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <div>
                            <span class="h2 mb-0 text-white d-block">{{ $wishlist->name }}</span>
                            <span class="text-white">{{ __('Ønskeliste') }}</span>
                        </div>
                        <div>
                            <span class="mr-2 text-white d-none d-sm-inline-block opacity-7">{{ __('Del ønskelisten:') }}</span>
                            <button data-clipboard-action="copy" data-clipboard-text="{{URL::to('/share/'.$wishlist->share_id)}}" class="cb-btn icon icon-primary icon-shape icon-sm py-0 mr-1"><i class="fas fa-link"></i></button>
                        </div>
                    </div>
                    <!-- Navigation -->
                    <div class="d-flex">
                        <div class="btn-group-nav" role="group">
                            <a href="{{ route('wishlists.edit', ['id' => $wishlist->id]) }}"
                               class="btn btn-icon shadow btn-neutral">
                                <span class="btn-inner--icon"><i class="far fa-edit"></i></span>
                                <span class="btn-inner--text d-none d-md-inline-block">{{ __('Rediger') }}</span>
                            </a>
                            <form method="POST" class="delete action-item p-0 mr-2" id="form"
                                  onclick="return confirm('{{ __('Er du sikker du ønsker at slette ønskelisten?') }}')"
                                  action="{{ route('wishlists.destroy', ['id' => $wishlist->id]) }}">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-icon shadow btn-neutral">
                                    <span class="btn-inner--icon p-0"><i class="far fa-trash-alt"></i></span>
                                    <span class="btn-inner--text d-none d-md-inline-block">{{ __('Slet') }}</span>
                                </button>
                            </form>
                            <a href="{{route('wishlist.printpdf', ['id' => $wishlist->id])}}"
                               class="btn btn-icon shadow btn-neutral">
                                <span class="btn-inner--icon"><i class="fas fa-print"></i></span>
                                <span class="btn-inner--text d-none d-md-inline-block">{{ __('Print') }}</span>
                            </a>
                        </div>
                        <div class="btn-group-nav ml-auto" role="group">
                            <button data-target=".create-wish" data-toggle="modal"
                                    class="btn btn-icon shadow btn-warning mr-0">
                                <span class="btn-inner--icon"><i class="fas fa-plus-circle fa-lg"></i></span>
                                <span class="btn-inner--text d-none d-sm-inline-block">{{ __('Opret ønske') }}</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Wishes -->
    @include('wishes.index')
    <!-- Create wish modal -->
    <div class="modal fade create-wish" tabindex="-1" role="dialog"
         aria-labelledby="create-wish" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
                <button type="button" class="btn btn-secondary modal-close m-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="p-5">
                    <div class="row">
                        <div class="col-12 col-lg-5 text-center">
                            <h4>{{ __('Opret automatisk') }}</h4>
                            <div class="mb-4">{{ __('Indsæt et link og hent automatisk information om ønsket.') }}</div>
                            <form method="POST" action="{{ route('wishes.create') }}">
                                @csrf
                                <div class="d-flex align-items-center mb-2">
                                    <input name="wishlist" type="hidden" value="{{ $wishlist->id }}">
                                    <input type="text" id="link" class="form-control" name="link"
                                           placeholder="{{__('Indsæt link') }}" required>
                                    <button type="submit" class="btn btn-warning ml-3">{{ __('Næste') }}</button>
                                </div>
                            </form>
                        </div>
                        <hr class="divider divider-vertical h-auto d-none d-lg-block my-0"/>
                        <hr class="divider divider-horizontal d-block d-lg-none my-5"/>
                        <div class="col-12 col-lg-5 text-center">
                            <h4>{{ __('Opret manuelt') }}</h4>
                            <div class="mb-4">{{ __('Opret manuelt, ved selv at indtaste information om ønsket.') }}</div>
                            <form method="POST" action="{{ route('wishes.create') }}">
                                @csrf
                                <input name="wishlist" type="hidden" value="{{ $wishlist->id }}">
                                <button type="submit" class="btn btn-warning ml-3">{{ __('Opret manuelt') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection