routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('index');
});

Route::get('/home', 'HomeController@index')->name('home');

// Wishlist
Route::resource('wishlists', 'WishListController');
Route::get('wishlists/{wishlist}/print-pdf', 'PrintController@printPDF')->name('wishlist.printpdf');


// Wishes
Route::resource('wishes', 'WishController');
Route::post('wishes/create/{id?}', 'WishController@create')->name('wishes.create');

// Share
Route::get('share/{id}', 'ShareController@show')->name('share.show');
Route::patch('share/reserve/{wish}', 'ShareController@reserve')->name('share.reserve');
Route::patch('share/delete-reserve/{wish}', 'ShareController@deleteReserve')->name('share.delete-reserve');

// Users
Route::get('profile/', 'UserController@show')->name('profile');
Route::patch('profile/{user}/', 'UserController@update')->name('users.update');
Route::patch('profile/password/{user}/', 'UserController@updatePassword')->name('users.update-password');
Route::delete('profile/delete/{user}/', 'UserController@destroy')->name('users.destroy');

// Auth
Auth::routes();

app/Wish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wish extends Model
{
    protected $fillable = [
        'name', 'description', 'price', 'link',
    ];

    public function wishlist()
    {
        return $this->belongsTo(Wishlist::class);
    }
}

app/Http/Controllers/WishController.php
<?php

namespace App\Http\Controllers;

use App\Traits\ScraperImageTrait;
use App\Traits\ScraperTrait;
use App\Traits\UploadImageTrait;
use App\Wish;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\File;

class WishController extends Controller
{
    use ScraperImageTrait;
    use ScraperTrait;
    use UploadImageTrait;

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        abort(404);
    }

    public function create(Request $request)
    {
        if (request('link')) {
            $scraper = $this->scraper(request('link'));
            $link = request('link');
            if ($scraper['image']) {
                // Upload scraper image and return file path
                $filePath = $this->scraperImage($scraper['image']);
                // Create session with file path
                $request->session()->put('filepath', $filePath);
            } else {
                $request->session()->forget('filepath');
            }
        } else {
            $request->session()->forget('filepath');
            $scraper = null;
            $link = null;
        }

        $wishListRequest = Auth::User()->wishlists->where('id', request('wishlist'))->first();
        if ($wishListRequest) {
            $selected_wishlist = $wishListRequest;
        } else {
            $selected_wishlist = Auth::User()->wishlists->last();
        }

        $wishlists = Auth::User()->wishlists()->orderBy('created_at', 'desc')->get();

        $missing_items = false;
        if($scraper['name'] === null || $scraper['image'] === null || $scraper['price'] === null) {
            $missing_items = true;
        }

        return view('wishes.create')->with('wishlists', $wishlists)->with('selected_wishlist',
            $selected_wishlist)->with('scraper', $scraper)->with('link', $link)->with('missing_items', $missing_items);
    }

    public function store(Request $request)
    {
        $request->validate([
            'image' => 'image|mimes:jpeg,png,jpg,gif|max:2048'
        ]);

        $wish = new Wish;
        $wish->fill(request()->all());
        $wish->wish_list_id = Crypt::decrypt(request('wish_list_id'));
        if ($request->has('image')) {
            // Upload image from request
            $wish->image = $this->uploadImage($request->file('image'));
        } elseif ($request->session()->get('filepath')) {
            // Upload image from session (from scraper)
            $wish->image = $request->session()->get('filepath');
        }
        $wish->save();

        session()->flash('success', __('Ønsket blev oprettet.'));
        return redirect('/wishlists/' . Crypt::decrypt(request('wish_list_id')));
    }

    public function show()
    {
        return abort(404);
    }

    public function edit(Wish $wish)
    {
        if (Auth::User()->isPartOfWish($wish)) {
            $wishlists = Auth::User()->wishlists()->orderBy('created_at', 'desc')->get();

            return view('wishes.edit')->with('wish', $wish)->with('wishlists', $wishlists);
        } else {
            return abort(403);
        }
    }

    public function update(Wish $wish)
    {
        if (Auth::User()->isPartOfWish($wish)) {
            $wish->fill(request()->all());
            $wish->wish_list_id = Crypt::decrypt(request('wish_list_id'));
            $wish->save();

            session()->flash('success', __('Ønsket blev opdateret.'));
            return redirect('/wishlists/' . $wish->wish_list_id);
        } else {
            return abort(403);
        }
    }

    public function destroy(Wish $wish)
    {
        if (Auth::User()->isPartOfWish($wish)) {
            $filePath = public_path() . $wish->image;
            if (file_exists($filePath)) {
                File::delete($filePath);
            }
            $wish->delete();

            session()->flash('success', __('Ønsket blev slettet.'));
            return back();
        } else {
            return abort(403);
        }
    }
}

resources/views/wishes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="header-account-page bg-primary d-flex align-items-end" data-offset-top="#header-main">
        <!-- Circles -->
    @include('partials.circles')
    <!-- Header -->
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Title -->
                    <div class="row align-items-center mb-4">
                        <div class="col-md-5 mb-4 mb-md-0">
                            <span class="h2 mb-0 text-white d-block">{{ __('Opret ønske') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Create wish  -->
    <section class="slice bg-section-secondary">
        <div class="container mn-5">
            <div class="row">
                <div class="col-12">
                    <div class="card zindex-100">
                        <div class="card-body px-md-5 py-5">
                            @if($missing_items)
                                <div class="mb-4">
                                    <span class="badge badge-soft-info badge-pill">
                                        Vi kunne desværre ikke finde alle informationer på dit ønske. Udfyld venligst selv de manglende informationer i felterne nedenfor.
                                    </span>
                                </div>
                            @endif
                            <form method="POST" action="{{ route('wishes.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-12 col-md-5">
                                        <div class="form-group">
                                            <label for="wish_list_id"
                                                   class="form-control-label">{{ __('Vælg ønskeliste') }}</label>
                                            <select name="wish_list_id" id="wish_list_id" class="custom-select"
                                                    data-toggle="select" required>
                                                @foreach($wishlists as $wishlist)
                                                    <option value="{{ Crypt::encrypt($wishlist->id) }}"
                                                            @if($wishlist->id === $selected_wishlist->id) selected @endif>{{ $wishlist->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        @if(Session::get("filepath"))
                                            <div class="form-control-label">{{ __('Billede') }}</div>
                                            <img style="width: 80% !important;"
                                                 src="{!! asset(Session::get("filepath")) !!}">
                                        @else
                                            <div class="form-group">
                                                <label for="image"
                                                       class="form-control-label">{{ __('Billede') }}</label>
                                                <input type="file" name="image" id="image" class="custom-input-file"/>
                                                <label for="image">
                                                    <i class="fa fa-upload"></i>
                                                    <span>{{ __('Tilføj billede') }}</span>
                                                </label>
                                                <small class="form-text text-muted mt-2">{{ __('Tilføj et billede, der viser hvad du ønsker dig') }}</small>
                                            </div>
                                        @endif
                                    </div>
                                    <div class="col-12 col-md-7">
                                        <div class="form-group">
                                            <label for="name" class="form-control-label">{{ __('Titel') }}</label>
                                            <input type="text" id="name" class="form-control" name="name"
                                                   value="@if($scraper['name']){!! $scraper['name'] !!}@else{{ old('name') }}@endif"
                                                   placeholder="{{__('Giv dit ønske en titel') }}" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="description"
                                                   class="form-control-label">{{ __('Beskrivelse') }}</label>
                                            <textarea id="description" class="form-control" name="description"
                                                      placeholder="{{__('Tilføj en beskrivelse til dit ønske. Farve, antal, størrelse eller andre detaljer, der er værdi at vide for dem, der skal købe det') }}">{{ old('description') }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="price" class="form-control-label">{{ __('Pris') }}</label>
                                            <input type="number" id="price" class="form-control" name="price"
                                                   value="@if($scraper['price']){!! $scraper['price'] !!}@else{{ old('price') }}@endif"
                                                   placeholder="{{__('Tilføj en pris') }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="link" class="form-control-label">{{ __('Link') }}</label>
                                            <input type="text" id="link" class="form-control" name="link"
                                                   value="@if($link){!! $link !!}@else{{ old('link') }}@endif"
                                                   placeholder="{{__('Tilføj et link, hvis ønsket kan købes online') }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-warning">{{ __('Opret ønske') }}</button>
                                    <a href="{{ URL::previous() }}"
                                       class="btn btn-link text-muted">{{ __('Annuller') }}</a>
                                </div>
                                @if ($errors->any())
                                    <div class="small text-danger mt-3" role="alert">
                                        <strong>{{ $errors->first() }}</strong>
                                    </div>
                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/wishes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="header-account-page bg-primary d-flex align-items-end" data-offset-top="#header-main">
        <!-- Circles -->
    @include('partials.circles')
    <!-- Header -->
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Title -->
                    <div class="row align-items-center mb-4">
                        <div class="col-md-5 mb-4 mb-md-0">
                            <span class="h2 mb-0 text-white d-block">{{ __('Rediger ønske') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Create wish  -->
    <section class="slice bg-section-secondary">
        <div class="container mn-5">
            <div class="row">
                <div class="col-12">
                    <div class="card zindex-100">
                        <div class="card-body px-md-5 py-5">
                            <form method="POST" action="{{ route('wishes.update', ['id' => $wish->id]) }}">
                                @method('PATCH')
                                @csrf
                                <div class="row">
                                    <div class="col-12 col-md-5">
                                        <div class="form-group">
                                            <label for="wish_list_id" class="form-control-label">{{ __('Vælg ønskeliste') }}</label>
                                            <select name="wish_list_id" id="wish_list_id" class="custom-select" data-toggle="select" required>
                                                @foreach($wishlists as $wishlist)
                                                    <option value="{{ Crypt::encrypt($wishlist->id) }}" @if($wishlist->id === $wish->wish_list_id) selected @endif>{{ $wishlist->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-control-label">{{ __('Billede') }}</div>
                                        <div class="bg-img-lg my-3">
                                            <img src="{{$wish->image}}" class="img-center img-fluid">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-7">
                                        <div class="form-group">
                                            <label for="name" class="form-control-label">{{ __('Titel') }}</label>
                                            <input type="text" id="name" class="form-control" name="name" value="{{ $wish->name }}" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="description" class="form-control-label">{{ __('Beskrivelse') }}</label>
                                            <textarea  id="description" class="form-control" name="description">{{ $wish->description }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="price" class="form-control-label">{{ __('Pris') }}</label>
                                            <input type="number" id="price" class="form-control" name="price" value="{{ $wish->price }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="link" class="form-control-label">{{ __('Link') }}</label>
                                            <input type="text" id="link" class="form-control" name="link" value="{{ $wish->link }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-warning">{{ __('Gem') }}</button>
                                    <a href="{{ URL::previous() }}"
                                       class="btn btn-link text-muted">{{ __('Annuller') }}</a>
                                </div>
                                @if ($errors->any())
                                    <div class="small text-danger mt-3" role="alert">
                                        <strong>{{ $errors->first() }}</strong>
                                    </div>
                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/wishes/index.blade.php
<section class="slice slice-lg delimiter-bottom bg-section-secondary">
    <div class="container">
        <div class="actions-toolbar py-2 mb-4">
            <h5 class="mb-1">{{ __('Ønsker') }}</h5>
            <p class="text-sm text-muted mb-0">{{ __('Opret, rediger og slet ønsker.') }}</p>
        </div>
        <div class="row">
        @foreach($wishes as $wish)
            <!-- Large modal -->
                <div class="modal fade wish-{{$wish->id}}" tabindex="-1" role="dialog"
                     aria-labelledby="wish-{{$wish->id}}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-lg">
                        <div class="modal-content">
                            <button type="button" class="btn btn-secondary modal-close m-0" data-dismiss="modal"
                                    aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-12 col-lg-5">
                                        @if($wish->image)
                                            <div class="bg-img-lg">
                                                <img src="{!! asset($wish->image) !!}"
                                                     class="img-center img-fluid">
                                            </div>
                                        @else
                                            <div class="bg-img-lg">
                                                <img src="{{asset('images/svg/illustrations/gift.svg')}}"
                                                     class="opacity-5 img-placeholder">
                                            </div>
                                        @endif
                                    </div>
                                    <div class="col-12 col-lg-7 d-flex flex-column">
                                        <div class="h3 my-4 mt-lg-0">{{ $wish->name }}</div>
                                        @isset($wish->description)
                                            <p class="mb-4">
                                                {{ $wish->description }}
                                            </p>
                                        @endisset
                                        @isset($wish->price)
                                            <div class="card-price mb-4"><span class="font-weight-bold h6">{{ $wish->price }}
                                                    <span class="text-sm">{{ __('kr') }}</span></span></div>
                                        @endisset
                                        <div class="d-flex mt-auto justify-content-end">
                                            <form method="POST" class="delete action-item p-0 mr-2" id="form"
                                                  onclick="return confirm('{{ __('Er du sikker du ønsker at slette ønsket?') }}')"
                                                  action="{{ route('wishes.destroy', ['id' => $wish->id]) }}">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-sm btn-outline-primary"><i
                                                            class="far fa-trash-alt"></i></button>
                                            </form>
                                            <a href="{{ route('wishes.edit', ['id' => $wish->id]) }}"
                                               class="btn btn-sm btn-outline-primary">
                                                {{ __('Rediger') }}
                                            </a>
                                            <a href="{{ $wish->link }}" target="_blank" class="btn btn-sm btn-outline-primary">
                                                {{ __('Link til ønske') }}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-6 col-lg-4 col-xl-3 d-flex">
                    <div class="wish__item card hover-shadow-lg hover-translate-y-n3 flex-fill">
                        @if($wish->image)
                            <div class="bg-img m-4">
                                <img src="{!! asset($wish->image) !!}"
                                     class="img-center img-fluid">
                            </div>
                        @else
                            <div class="bg-img m-4">
                                <img src="{{asset('images/svg/illustrations/gift.svg')}}"
                                     class="opacity-5 img-placeholder">
                            </div>
                        @endif
                        <div class="card-body text-center d-flex flex-column pt-0">
                            <strong class="h6 m-0 p-0 pb-2">
                                <a href="#" data-target=".wish-{{$wish->id}}" data-toggle="modal">{{ $wish->name }}</a>
                            </strong>
                            @isset($wish->description)
                                <p class="text-sm">
                                    {{ str_limit($wish->description, 50, '...') }}
                                </p>
                            @endisset
                            @isset($wish->price)
                                <div class="card-price mt-auto"><span class="font-weight-bold h6">{{ $wish->price }}
                                        <span class="text-sm">{{ __('kr') }}</span></span></div>
                            @endisset
                        </div>
                        <div class="card-footer py-2">
                            <div class="actions d-flex justify-content-between">
                                <div>
                                    <a href="{{ route('wishes.edit', ['id' => $wish->id]) }}"
                                       class="delete action-item mr-2">
                                        <i class="far fa-edit"></i>
                                    </a>
                                    <form method="POST" class="delete action-item" id="form"
                                          onclick="return confirm('{{ __('Er du sikker du ønsker at slette ønsket?') }}')"
                                          action="{{ route('wishes.destroy', ['id' => $wish->id]) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="action-item text-danger ml-2">
                                            <i class="far fa-trash-alt"></i>
                                        </button>
                                    </form>
                                </div>
                                <strong class="h6 text-sm d-flex align-items-center m-0 pr-2">
                                    <a href="#" data-target=".wish-{{$wish->id}}"
                                       data-toggle="modal">{{ __('Se ønske') }}</a>
                                </strong>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            <div class="col-xl-3 col-lg-4 col-sm-6 d-flex">
                <div data-target=".create-wish" data-toggle="modal"
                   class="wish__item card border-md border-dashed bg-transparent shadow-none flex-fill" style="cursor: pointer;">
                    <div class="card-body text-center d-flex flex-column align-items-center justify-content-center p-5">
                        <button type="button" class="btn btn-soft-warning rounded-circle btn-icon-only mr-0">
                                <span class="btn-inner--icon">
                                    <i class="fas fa-plus"></i>
                                </span>
                        </button>
                        <div class="mt-4 h6 text-muted">{{ __('Opret nyt ønske') }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>